spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: shopping_cart_service_route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**
          filters:
            - PrefixPath=/api/v1

        - id: shopping_store_service_route
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store/**
          filters:
            - PrefixPath=/api/v1
            - name: Retry
              args:
                retries: 3
                statuses: NOT_FOUND
                methods: GET,POST,PUT
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: warehouse_service_route
          uri: lb://warehouse
          predicates:
            - Path=/warehouse/**
          filters:
            - PrefixPath=/api/v1

        - id: order_service_route
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - PrefixPath=/api/v1

        - id: payment_service_route
          uri: lb://payment
          predicates:
            - Path=/payment/**
          filters:
            - PrefixPath=/api/v1

        - id: delivery_service_route
          uri: lb://delivery
          predicates:
            - Path=/delivery/**
          filters:
            - PrefixPath=/api/v1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes,beans,env
      base-path: /actuator
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.server: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.discovery: DEBUG